import difflib
from pathlib import Path

from email_sort.config import get_section_setting
from email_sort.db import get_db


def _escape(value: str) -> str:
    return (value or "").replace("\\", "\\\\").replace('"', '\\"')


def _address_test(sender: str) -> str:
    sender = _escape(sender)
    if sender.startswith("@"):
        return f'address :domain "from" "{sender[1:]}"'
    return f'address "from" "{sender}"'


def generate_sieve(output_path: str | None = None) -> str:
    lines = ['require ["fileinto", "reject"];', "", "# Generated by email-sort", ""]
    conn = get_db()
    try:
        cursor = conn.cursor()
        cursor.execute(
            """
            SELECT sender FROM sender_stats
            WHERE has_user_reply = 1
            ORDER BY sender
            """
        )
        for row in cursor.fetchall():
            lines.extend(
                [f"if {_address_test(row['sender'])} {{", "    keep;", "    stop;", "}", ""]
            )

        cursor.execute("SELECT sender, override_category FROM sender_overrides ORDER BY sender")
        for row in cursor.fetchall():
            folder = _escape(row["override_category"] or "Other")
            lines.extend(
                [
                    f"if {_address_test(row['sender'])} {{",
                    f'    fileinto "{folder}";',
                    "    stop;",
                    "}",
                    "",
                ]
            )

        cursor.execute(
            """
            SELECT sender FROM sender_stats
            WHERE total_emails >= 10 AND spam_ratio >= 0.9 AND has_user_reply = 0
            ORDER BY total_emails DESC
            """
        )
        for row in cursor.fetchall():
            lines.extend(
                [
                    f"if {_address_test(row['sender'])} {{",
                    '    fileinto "Spam";',
                    "    stop;",
                    "}",
                    "",
                ]
            )

        cursor.execute(
            """
            SELECT sender FROM sender_stats
            WHERE total_emails >= 10 AND promotional_ratio >= 0.9 AND has_user_reply = 0
            ORDER BY total_emails DESC
            """
        )
        for row in cursor.fetchall():
            lines.extend(
                [
                    f"if {_address_test(row['sender'])} {{",
                    '    fileinto "Promotional";',
                    "    stop;",
                    "}",
                    "",
                ]
            )

        cursor.execute(
            """
            SELECT DISTINCT sender FROM fastmail WHERE dmarc_fail = 1 AND has_arc = 0
            UNION
            SELECT DISTINCT sender FROM google_emails WHERE dmarc_fail = 1 AND has_arc = 0
            """
        )
        for row in cursor.fetchall():
            lines.extend(
                [
                    f"if {_address_test(row['sender'])} {{",
                    '    fileinto "Suspicious";',
                    "    stop;",
                    "}",
                    "",
                ]
            )
    finally:
        conn.close()

    script = "\n".join(lines).rstrip() + "\n"
    if output_path:
        path = Path(output_path)
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(script)
    return script


def _client():
    from sievelib.factory import ManageSieveClient

    host = get_section_setting("sieve", "host")
    port = int(get_section_setting("sieve", "port", 4190))
    username = get_section_setting("sieve", "username")
    password = get_section_setting("sieve", "password")
    if not host or not username or not password:
        raise ValueError("Missing [sieve] host, username, or password")
    client = ManageSieveClient(host, port)
    client.login(username, password)
    return client


def upload_sieve(local_file: str) -> None:
    script = Path(local_file).read_text()
    client = _client()
    try:
        client.putscript("email-sort", script)
        client.setactive("email-sort")
    finally:
        client.logout()


def diff_sieve(local_file: str) -> str:
    local = Path(local_file).read_text()
    client = _client()
    try:
        active_name = None
        for name in client.listscripts()[0]:
            if client.isactive(name):
                active_name = name
                break
        remote = client.getscript(active_name)[1] if active_name else ""
    finally:
        client.logout()
    return "".join(
        difflib.unified_diff(
            remote.splitlines(keepends=True),
            local.splitlines(keepends=True),
            fromfile="remote-active",
            tofile=local_file,
        )
    )
